"""
Django settings for nexxo_cms project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os  # Necessário para os caminhos de MEDIA e STATIC

#Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

<<<<<<< HEAD
=======
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

>>>>>>> 8c61ace3cb8eb645de17337dedd848e18d3ba571
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hnk4d@gqr7sh^=%j$-i49sfk)_3=668fek(yt$!w&f99rex#8o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # Sua aplicação principal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Essencial para formulários POST
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nexxo_cms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Deixe vazio se os templates estão dentro dos apps
        'APP_DIRS': True, # Permite que o Django encontre templates dentro dos apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Necessário para Admin e request
                'django.contrib.auth.context_processors.auth', # Necessário para Admin e login
                'django.contrib.messages.context_processors.messages', # Necessário para Admin e mensagens
            ],
        },
    },
]

WSGI_APPLICATION = 'nexxo_cms.wsgi.application'


# Database
# Configurado para usar SQLite para desenvolvimento (sem servidor MySQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""
# Bloco MySQL comentado para referência futura:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'db', 
#         'USER': 'root', 
#         'PASSWORD': 'root', 
#         'HOST': 'localhost', 
#         'PORT': '3306', 
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }
"""

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br' # Mudado para português do Brasil

TIME_ZONE = 'America/Sao_Paulo' # Mudado para fuso horário de São Paulo

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Diretório onde o Django deve procurar arquivos estáticos fora dos apps
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'), # Adiciona a pasta 'static' do seu app 'core'
]

# Media files (User uploaded files)
# Onde os arquivos de upload serão salvos (ex: temp_uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# URL base para acessar os arquivos de mídia
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuração para o redirecionamento de login
LOGIN_URL = '/login/' # URL da sua tela de login customizada
LOGIN_REDIRECT_URL = '/gerenciar/' # URL para onde o usuário vai após o login
LOGOUT_REDIRECT_URL = '/' # Opcional: para onde ir após logout