# Generated by Django 5.2.6 on 2025-10-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Mídia')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo (MP4, MOV)'), ('IMAGEM', 'Imagem (JPG, PNG)'), ('HTML', 'HTML/Web (Anúncio Externo)')], default='VIDEO', max_length=10, verbose_name='Tipo de Mídia')),
                ('arquivo_upload', models.FileField(blank=True, null=True, upload_to='temp_uploads/', verbose_name='Arquivo de Upload')),
                ('url_publica', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Exibição (Cloud)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ativo', max_length=50)),
                ('duracao', models.IntegerField(blank=True, null=True, verbose_name='Duração (Segundos)')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título da Playlist')),
                ('ativa', models.BooleanField(default=False, verbose_name='Playlist Ativa?')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDispositivo', models.CharField(max_length=255, verbose_name='Nome do Dispositivo')),
                ('codVerificacao', models.CharField(max_length=50, unique=True, verbose_name='Código de Verificação')),
                ('status', models.CharField(default='ativo', max_length=20, verbose_name='Status')),
                ('playlistAssociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playlist', verbose_name='Playlist Associada')),
                ('tipoDispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodispositivo', verbose_name='Tipo de Dispositivo')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='ItemPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem de Exibição')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.midia')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.playlist')),
            ],
            options={
                'verbose_name': 'Item da Playlist',
                'verbose_name_plural': 'Itens da Playlist',
                'ordering': ['ordem'],
                'unique_together': {('playlist', 'ordem')},
            },
        ),
    ]
