# Generated by Django 5.2.6 on 2025-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ativo', max_length=50)),
                ('duracao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mídias',
            },
        ),
    ]
