# Generated by Django 5.2.6 on 2025-10-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título da Playlist')),
                ('ativa', models.BooleanField(default=False, verbose_name='Playlist Ativa')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlaylistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem de Exibição')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.midia')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.playlistdb')),
            ],
            options={
                'verbose_name': 'Item da Playlist',
                'verbose_name_plural': 'Itens da Playlist',
                'ordering': ['ordem'],
                'unique_together': {('playlist', 'ordem')},
            },
        ),
    ]
