# Generated by Django 5.2.6 on 2025-10-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playlistdb_itemplaylistdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPlaylistDB',
            new_name='ItemPlaylist',
        ),
        migrations.RenameModel(
            old_name='PlaylistDB',
            new_name='Playlist',
        ),
        migrations.AlterModelOptions(
            name='itemplaylist',
            options={'ordering': ['ordem']},
        ),
    ]
