# Generated by Django 5.2.6 on 2025-10-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_itemplaylistdb_itemplaylist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoFormato',
            fields=[
                ('id', models.AutoField(db_column='Id_Tipo_Midia', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'tipos_midia',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='midia',
            name='url',
        ),
        migrations.AddField(
            model_name='midia',
            name='arquivo_upload',
            field=models.FileField(blank=True, null=True, upload_to='temp_uploads/', verbose_name='Arquivo de Upload'),
        ),
        migrations.AddField(
            model_name='midia',
            name='url_publica',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Exibição (Cloud)'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo de Mídia'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título da Mídia'),
        ),
    ]
