# Generated by Django 5.2.6 on 2025-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipoformato_remove_midia_url_midia_arquivo_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.AutoField(db_column='Id_Tipo_Dispositivo', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'tipos_dispositivo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='tipoFormato',
        ),
        migrations.AlterField(
            model_name='midia',
            name='duracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração (Segundos)'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Vídeo (MP4, MOV)'), ('IMAGEM', 'Imagem (JPG, PNG)'), ('HTML', 'HTML/Web (Anúncio Externo)')], default='VIDEO', max_length=10, verbose_name='Tipo de Mídia'),
        ),
    ]
