# Generated by Django 5.2.6 on 2025-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipodispositivo_delete_tipoformato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('idDispositivo', models.AutoField(db_column='Id_Dispositivo', primary_key=True, serialize=False)),
                ('nomeDispositivo', models.CharField(db_column='Nome', max_length=255)),
                ('codVerificacao', models.CharField(db_column='Codigo_Verificacao', max_length=255, unique=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': False,
            },
        ),
    ]
