# Generated by Django 5.2.6 on 2025-10-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dispositivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={},
        ),
    ]
