# Generated by Django 5.2.6 on 2025-10-24 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dispositivo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='tipodispositivo',
            options={'verbose_name_plural': 'Tipos de Dispositivo'},
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='idDispositivo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='playlistAssociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playlist', verbose_name='Playlist Ativa'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipoDispositivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='codVerificacao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Verificação'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nomeDispositivo',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='dispositivo',
            table=None,
        ),
    ]
