# Generated by Django 5.2.6 on 2025-10-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dispositivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodispositivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tipo'),
        ),
        migrations.AlterModelTable(
            name='tipodispositivo',
            table=None,
        ),
    ]
